# Generated by Django 2.2.19 on 2022-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220909_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Pizza_desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Pizza_price',
            field=models.FloatField(max_length=100),
        ),
    ]
