# Generated by Django 2.2.19 on 2022-11-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0006_auto_20220913_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Pizza_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Pizza_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Pizza_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Pizza_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Pizza_price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Image', models.ImageField(blank=True, default='image/defaultuser.png', null=True, upload_to='images')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
